title:             A new start Blog
email:             musong3@gmail.com
description:       Get ready for the new world
author:            shins94
baseurl:           ""
url:               "https://shins94.github.io"

# Social Profiles
twitter_username:  musong3
github_username:   shins94
linkedin_username:  shins94
# facebook_username: StartBootstrap
disqus_site_id: shins94
# Build settings
highlightjs_theme: "monokai_sublime"
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
category_dir: category/

# The font used for headings. Expects a string that is a valid CSS font-family value.
font_heading:        "'Roboto Slab', 'Nanum Gothic', Helvetica, Arial, sans-serif"

# The text font. Expects a string that is a valid CSS font-family value.
font:                "'Noto Sans', 'Nanum Gothic', Helvetica, Arial, sans-serif"

# The string encoding what fonts to fetch from Google Fonts.
# See: https://qwtel.com/hydejack/docs/configuration/
google_fonts:        Roboto+Slab:700|Noto+Sans:400,400i,700,700i

# If you do not use a Google Fonts, uncomment the line below
# no_google_fonts:     true
