title:             A new start Blog
email:             musong3@gmail.com
description:       Get ready for the new world
author:            shins94
baseurl:           ""
url:               "https://shins94.github.io"

# Social Profiles
twitter_username:  musong3
github_username:   shins94
# facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
